management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: padTimezoneChangeTopic
          content-type: application/json
      kafka:
        binder:
          zkNodes: kafkaserver
          brokers: kafkaserver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/66d0dc3b-f35c-4f5b-b473-86c93172e100/v2.0
          #          jwk-set-uri: https://devlinqxfracpro.b2clogin.com/devlinqxfracpro.onmicrosoft.com/B2C_1_signin_sigup_test_manmohan/discovery/v2.0/keys
          jwk-set-uri: https://devlinqxfracpro.b2clogin.com/devlinqxfracpro.onmicrosoft.com/B2C_1_DevAI_UF_Sign-In/discovery/v2.0/keys
  data:
    mongodb:
      uri: mongodb
      port: 27017
      database: FracProOps
      username: carbo
      password: carbor0x!

server:
  port: 9083

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user



#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.carbo: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /api/pad/v3/api-docs/swagger-config
    url: /api/pad/v3/api-docs/all-service-api

api:
  fracpro:
    v1:
      wellsDirect: https://api.fracpro.ai:4000/api/v1/wells/

fracpro:
  protocol: https
  server: api.fracpro.ai
  port: 4000
  username: xxxxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxxx
